version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: '21:00'
    timezone: Asia/Manila
  open-pull-requests-limit: 10

  default_labels: 
    - "automated"
