name: Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Generate Reports
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch recent updates
      run: git fetch --prune --unshallow

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.6

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Generate test coverage data
      run: ./gradlew -Pversion=20.2.0-SNAPSHOT build jacocoTestReport      

    - name: Generate Sonarqube report
      run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.dbcleaner.daysBeforeDeletingInactiveShortLivingBranches=30
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Generate Codecov report
      uses: codecov/codecov-action@v1.0.7
      with:
        # User defined upload name. Visible in Codecov UI
        name: Argos
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
