# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch recent updates
      run: git fetch --prune --unshallow
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.6
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Upload environment artifact
      uses: actions/upload-artifact@v2
      with:
        name: environment
        path: ./
    
  build-and-test:
    name: Build and test
    needs: prepare
    runs-on: ubuntu-latest

    steps:
    - name: Get environment artifact
      uses: actions/download-artifact@v2
      with:
        name: environment
    - name: Build with Gradle
      run: ./gradlew build jacocoTestReport sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.dbcleaner.daysBeforeDeletingInactiveShortLivingBranches=30
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
