name: Gradle Version Updater

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  checker:
    name: Get latest version
    runs-on: ubuntu-latest
    
    steps:
      - name: Gradle Self Updater
        uses: rahulsom/gradle-up@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
