# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches: [ master, '!snapshot-**' ]
  pull_request:
    branches: [ master, '!snapshot-**' ]

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch recent updates
      run: git fetch --prune --unshallow

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.6

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
