name: PR Auto Merge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.8.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_LABELS: "automated"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: true
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "300000"
          UPDATE_METHOD: "rebase"
