name: Update SNAPSHOT Version
on: 
  milestone:
    types: [created, opened, edited]

jobs:
  update-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: Update release SNAPSHOT version 
        run: |
          echo version=${{ github.event.milestone.title }}-SNAPSHOT > gradle.properties
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add gradle.properties
          git commit -m "Bump project version to ${{ github.event.milestone.title }}-SNAPSHOT"
          
      - name: Push changes
        id: pushChanges
        uses: ad-m/github-push-action@master
        with:
          branch: snapshot-${{ github.event.milestone.title }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          title: 'Bump project version to ${{ github.event.milestone.title }}-SNAPSHOT'
          labels: automated
          milestone: ${{ github.event.milestone.title }}
          branch: snapshot-${{ github.event.milestone.title }}
